name: 99 - Copy issues from starter repo


env:
    GH_TOKEN: ${{ github.token }}
    STARTER: https://github.com/ucsb-cs156/proj-happycows
on:
  workflow_dispatch:
jobs:
  initialize:
    name: List Issues to JSON
    runs-on: ubuntu-latest
    outputs:
        issues: ${{ steps.get-issues.outputs.issues }}  

    steps:
      - uses: actions/checkout@v3
            
      - name: List Issues
        id: get-issues
        run: |
          GH_REPO=${{env.STARTER}} gh issue list -s open -l M23 --json number,title,labels > issues.json
          cat issues.json
          issues=`cat issues.json`
          echo "issues=${issues}"
          echo "issues=${issues}" >> "$GITHUB_OUTPUT"   

  addIssuesToRepo:
    name: Add issue (${{ matrix.value.number }}) to repo 
    runs-on: ubuntu-latest
    needs: [initialize]

    env:
      destination: target/site/apidocs  
      number: ${{ matrix.value.number }}
      title: ${{ toJSON(matrix.value.title) }} 
    strategy:
      matrix:
        value: ${{ fromJSON(needs.initialize.outputs.ISSUES)}}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.2

      - name: Display issue for debugging
        run: |
            echo number=${{env.number}}
            echo title=${{env.title}}
           

 
           


    

        