name: 99 - Copy issues from starter repo


env:
    GH_TOKEN: ${{ github.token }}
    STARTER: https://github.com/ucsb-cs156/proj-happycows
on:
  workflow_dispatch:
jobs:
  listIssuesToJson:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
            
    #   - name: Setup Python
    #     uses: actions/setup-python@v2
    #     with:
    #       python-version: '3.8'

      - name: List Issues
        run: |
          GH_REPO=${{env.STARTER}} gh issue list -s open -l M23 --json id,title,body,labels > issues.json
          cat issues.json   
          